run-tests-on-android.sh: more build server improvements.
Suppress these messages when using `adb shell -t` from a build server:

  Remote PTY will not be allocated because stdin is not a terminal.
  Use multiple -t options to force remote PTY allocation.

Also avoid this incorrect assumption:

  error: device offline
  -- mktemp not present

This should count as a failure instead, not "this is a test for
something that isn't on the device".

Test: still see escapes run interactively.
Bug: http://b/135744229
Change-Id: I1e6ad7fc6d5cbf4b208ad9e8ecbb51048caa3fbb