Update patch set 1
Patch Set 1:

> > > @Alexander toybox is still broken for me even after that change
 > > > (64-bit target).  Is your build succeeding?
 > >
 > > i am building with 64 bit as well (R7Plus) and it builds fine on
 > my
 > > end.
 > > I did not test a 32 bit target though..
 > 
 > Hmm, I have several other reports that it is still broken.  o_O

thats pretty weird, mmm works for me, but with a clean build it breaks.

if i pick this patch, mmm starts failing for me "error: implicit declaration of function 'basename' is invalid in C99"

Patch-set: 1
Label: Code-Review=0